spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false # Usa hostname (localhost) en lugar de IP

  client:
    register-with-eureka: false # No se registra a sí mismo
    fetch-registry: false       # No intenta obtener el registro
    service-url:
      defaultZone: http://localhost:8761/eureka

  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
